name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sudo apt-get install libgtest-dev google-mock
      run: sudo apt-get install libgtest-dev google-mock
    - name: git submodule init
      run: git submodule init
    - name: git submodule update
      run: git submodule update
    - name: make and run tests in debug mode
      run: mkdir build && cd build && cmake -DBUILD_CUBLAS=OFF .. && make -j4
